# Generated by Django 2.1.1 on 2019-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststorage',
            name='content',
            field=models.CharField(max_length=256),
        ),
    ]
