# Generated by Django 2.1.1 on 2019-07-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190719_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1999-04-30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poststorage',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='poststorage',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
