# Generated by Django 2.1.1 on 2019-07-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190719_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststorage',
            name='created_at',
        ),
    ]
